[profile.default]
evm_version = 'london'
libs = ['lib']
out = 'out'
remappings = [
  '@thirdweb-dev/=node_modules/@thirdweb-dev/',
  '@openzeppelin=node_modules/@openzeppelin',
]
src = 'src'
optimizer = true
optimizer_runs = 100
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
